// размеры фото пользователя в комментариях
const COMMENT_PICTURE_SIZE = 35;

const MAX_COMMENT_LENGTH = 140;
const MAX_NUMBER_OF_HASHTAGS = 5;
const SHOW_COMMENTS_STEP = 5;

//для сортировки фото
const IMAGE_QUANTITY = 10;
const DELAY_DURATION = 500;

export { COMMENT_PICTURE_SIZE, MAX_COMMENT_LENGTH, MAX_NUMBER_OF_HASHTAGS, SHOW_COMMENTS_STEP, IMAGE_QUANTITY, DELAY_DURATION };
